name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      with:
        node-version: latest
        eslint: true
      -run: make lint
